export const ApiErrorCode = {
  AUTH_ACCESS_TOKEN_INVALID: 'AUTH_ACCESS_TOKEN_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_CODE_EXPIRED: 'AUTH_CODE_EXPIRED',
  AUTH_CODE_DELIVERY_FAILED: 'AUTH_CODE_DELIVERY_FAILED',
  AUTH_CODE_INVALID: 'AUTH_CODE_INVALID',
  AUTH_CODE_RATE_LIMITED: 'AUTH_CODE_RATE_LIMITED',
  AUTH_PASSWORD_INVALID: 'AUTH_PASSWORD_INVALID',
  AUTH_PASSWORD_RESET_INVALID: 'AUTH_PASSWORD_RESET_INVALID',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_USER_DISABLED: 'AUTH_USER_DISABLED',
  DRIVER_ACCEPTANCE_OFFLINE: 'DRIVER_ACCEPTANCE_OFFLINE',
  DRIVER_CERTIFICATION_NOT_FOUND: 'DRIVER_CERTIFICATION_NOT_FOUND',
  DRIVER_CERTIFICATION_REQUIRED: 'DRIVER_CERTIFICATION_REQUIRED',
  DRIVER_WITHDRAWAL_BALANCE_INSUFFICIENT: 'DRIVER_WITHDRAWAL_BALANCE_INSUFFICIENT',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_PREVIEW_SIGNATURE_INVALID: 'FILE_PREVIEW_SIGNATURE_INVALID',
  FILE_PURPOSE_INVALID: 'FILE_PURPOSE_INVALID',
  FILE_STATE_INVALID: 'FILE_STATE_INVALID',
  FILE_STORAGE_CALLBACK_INVALID: 'FILE_STORAGE_CALLBACK_INVALID',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_DRAFT_CONFLICT: 'ORDER_DRAFT_CONFLICT',
  ORDER_STATE_INVALID: 'ORDER_STATE_INVALID',
  PROFILE_ADDRESS_BOOK_CONFLICT: 'PROFILE_ADDRESS_BOOK_CONFLICT',
  PROFILE_COUPON_NOT_AVAILABLE: 'PROFILE_COUPON_NOT_AVAILABLE',
  PROFILE_FREQUENT_ROUTES_CONFLICT: 'PROFILE_FREQUENT_ROUTES_CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];

export class BusinessError extends Error {
  constructor(
    public readonly code: ApiErrorCode,
    message: string,
  ) {
    super(message);
  }
}
