import { AdminPermissionMatrixService } from './admin-permission-matrix.service';

const NOW = new Date('2026-07-18T04:00:00.000Z');

describe('AdminPermissionMatrixService', () => {
  it('builds the first-slice admin permission matrix for current admin tools', async () => {
    const service = new AdminPermissionMatrixService(() => NOW);

    const matrix = await service.getMatrix();

    expect(matrix).toEqual(
      expect.objectContaining({
        generatedAtIso: NOW.toISOString(),
        defaultProfileKey: 'platform_admin',
        profileCount: 1,
        moduleCount: 15,
        capabilityCount: 15,
        writeCapabilityCount: 12,
        highRiskCapabilityCount: 12,
        remainingGaps: ['多角色拆分', '行级 / 数据域权限', '审批流 / 双人复核'],
        profiles: [
          expect.objectContaining({
            key: 'platform_admin',
            userType: 'admin',
            moduleKeys: expect.arrayContaining([
              'permission-matrix',
              'account-management',
              'driver-certification',
              'shipper-verification',
              'shipper-invoice',
              'order-change-request',
              'session-governance',
              'support-ticket',
              'finance',
            ]),
            capabilityKeys: expect.arrayContaining([
              'permission_matrix_read',
              'driver_certification_manage',
              'shipper_verification_manage',
              'shipper_invoice_manage',
              'order_management_manage',
              'order_change_request_manage',
              'account_management_manage',
              'session_governance_manage',
              'support_ticket_manage',
              'finance_manage',
            ]),
          }),
        ],
        modules: expect.arrayContaining([
          expect.objectContaining({
            key: 'permission-matrix',
            route: '/api/admin/permission-matrix-console',
            capabilityCount: 1,
            writeCapabilityCount: 0,
            highRiskCapabilityCount: 0,
          }),
          expect.objectContaining({
            key: 'session-governance',
            route: '/api/admin/session-governance-console',
            capabilityCount: 1,
            writeCapabilityCount: 1,
            highRiskCapabilityCount: 1,
          }),
          expect.objectContaining({
            key: 'shipper-verification',
            route: '/api/admin/shipper-verification-console',
            capabilityCount: 1,
            writeCapabilityCount: 1,
            highRiskCapabilityCount: 1,
          }),
          expect.objectContaining({
            key: 'shipper-invoice',
            route: '/api/admin/shipper-invoice-console',
            capabilityCount: 1,
            writeCapabilityCount: 1,
            highRiskCapabilityCount: 1,
          }),
          expect.objectContaining({
            key: 'support-ticket',
            route: '/api/admin/support-ticket-console',
            capabilityCount: 1,
            writeCapabilityCount: 1,
            highRiskCapabilityCount: 1,
            summary:
              '查看帮助中心工单列表/详情、SLA 提醒，并执行认领、强制接管、指派 / 转派、释放认领和 pending / processing / resolved 流程推进。',
          }),
          expect.objectContaining({
            key: 'order-exception-case',
            route: '/api/admin/order-exception-case-console',
            capabilityCount: 1,
            writeCapabilityCount: 1,
            highRiskCapabilityCount: 1,
            summary:
              '读取异常工单、查看详情，并能认领未认领工单、强制接管他人已认领工单、指派 / 转派给指定客服、释放认领后继续推进 processing / resolved / closed 流程。',
          }),
          expect.objectContaining({
            key: 'order-management',
            route: '/api/admin/order-management-console',
            capabilityCount: 1,
            writeCapabilityCount: 1,
            highRiskCapabilityCount: 1,
          }),
          expect.objectContaining({
            key: 'order-change-request',
            route: '/api/admin/order-change-request-console',
            capabilityCount: 1,
            writeCapabilityCount: 1,
            highRiskCapabilityCount: 1,
          }),
          expect.objectContaining({
            key: 'account-management',
            route: '/api/admin/account-management-console',
            capabilityCount: 1,
            writeCapabilityCount: 1,
            highRiskCapabilityCount: 1,
          }),
          expect.objectContaining({
            key: 'finance',
            route: '/api/admin/finance-console',
            capabilityCount: 1,
            writeCapabilityCount: 1,
            highRiskCapabilityCount: 1,
          }),
        ]),
        capabilities: expect.arrayContaining([
          expect.objectContaining({
            key: 'permission_matrix_read',
            moduleKey: 'permission-matrix',
            moduleTitle: '权限矩阵台',
            consoleRoute: '/api/admin/permission-matrix-console',
            actions: ['read'],
            riskLevel: 'normal',
            apiPaths: ['/admin/permissions/matrix'],
          }),
          expect.objectContaining({
            key: 'session_governance_manage',
            moduleKey: 'session-governance',
            actions: ['read', 'write'],
            riskLevel: 'high',
            apiPaths: expect.arrayContaining([
              '/admin/auth/sessions',
              '/admin/auth/sessions/{sessionId}/revoke',
            ]),
          }),
          expect.objectContaining({
            key: 'driver_certification_manage',
            moduleKey: 'driver-certification',
            moduleTitle: '司机认证审核台',
            consoleRoute: '/api/admin/driver-certification-console',
            actions: ['read', 'write'],
            riskLevel: 'high',
            apiPaths: expect.arrayContaining([
              '/admin/driver-certifications',
              '/admin/driver-certifications/{driverId}',
              '/admin/driver-certifications/{driverId}/attachments',
              '/admin/driver-certifications/{driverId}/review-events',
            ]),
          }),
          expect.objectContaining({
            key: 'shipper_verification_manage',
            moduleKey: 'shipper-verification',
            moduleTitle: '货主认证审核台',
            consoleRoute: '/api/admin/shipper-verification-console',
            actions: ['read', 'write'],
            riskLevel: 'high',
            apiPaths: expect.arrayContaining([
              '/admin/shipper-verifications',
              '/admin/shipper-verifications/{shipperId}',
              '/admin/shipper-verifications/{shipperId}/attachments',
              '/admin/shipper-verifications/{shipperId}/review-events',
              '/admin/shipper-verifications/{shipperId}/identity/review',
              '/admin/shipper-verifications/{shipperId}/enterprise/review',
            ]),
          }),
          expect.objectContaining({
            key: 'shipper_invoice_manage',
            moduleKey: 'shipper-invoice',
            moduleTitle: '发票申请审核台',
            consoleRoute: '/api/admin/shipper-invoice-console',
            actions: ['read', 'write'],
            riskLevel: 'high',
            apiPaths: expect.arrayContaining([
              '/admin/shipper-invoices',
              '/admin/shipper-invoices/{applicationId}',
              '/admin/shipper-invoices/{applicationId}/download',
              '/admin/shipper-invoices/{applicationId}/review-events',
              '/admin/shipper-invoices/{applicationId}/review',
            ]),
          }),
          expect.objectContaining({
            key: 'support_ticket_manage',
            moduleKey: 'support-ticket',
            moduleTitle: '帮助中心工单台',
            consoleRoute: '/api/admin/support-ticket-console',
            actions: ['read', 'write'],
            riskLevel: 'high',
            summary:
              '读取帮助中心工单列表/详情、SLA 提醒，并能执行 claim、takeover、assign、unclaim、process、resolve 状态流转与超时升级扫描。',
            apiPaths: expect.arrayContaining([
              '/admin/support-tickets',
              '/admin/support-tickets/overdue-escalations/sweep',
              '/admin/support-tickets/{ticketId}/claim',
              '/admin/support-tickets/{ticketId}/takeover',
              '/admin/support-tickets/{ticketId}/assign',
              '/admin/support-tickets/{ticketId}/unclaim',
              '/admin/support-tickets/{ticketId}/process',
            ]),
          }),
          expect.objectContaining({
            key: 'order_exception_case_manage',
            moduleKey: 'order-exception-case',
            moduleTitle: '异常客服工单台',
            consoleRoute: '/api/admin/order-exception-case-console',
            actions: ['read', 'write'],
            riskLevel: 'high',
            summary:
              '读取异常工单列表/详情，并能执行 claim、takeover、assign、unclaim、process、resolve、close 状态流转与超时升级扫描。',
            apiPaths: expect.arrayContaining([
              '/admin/order-exception-cases',
              '/admin/order-exception-cases/{caseId}',
              '/admin/order-exception-cases/overdue-escalations/sweep',
              '/admin/order-exception-cases/{caseId}/claim',
              '/admin/order-exception-cases/{caseId}/takeover',
              '/admin/order-exception-cases/{caseId}/assign',
              '/admin/order-exception-cases/{caseId}/unclaim',
              '/admin/order-exception-cases/{caseId}/process',
              '/admin/order-exception-cases/{caseId}/resolve',
              '/admin/order-exception-cases/{caseId}/close',
            ]),
          }),
          expect.objectContaining({
            key: 'order_management_manage',
            moduleKey: 'order-management',
            moduleTitle: '订单管理台',
            consoleRoute: '/api/admin/order-management-console',
            actions: ['read', 'write'],
            riskLevel: 'high',
            apiPaths: expect.arrayContaining([
              '/admin/orders',
              '/admin/orders/report',
              '/admin/orders/export',
              '/admin/orders/{orderId}',
              '/admin/orders/batch-cancel',
              '/admin/orders/{orderId}/cancel',
            ]),
          }),
          expect.objectContaining({
            key: 'order_change_request_manage',
            moduleKey: 'order-change-request',
            moduleTitle: '订单修改申请审核台',
            consoleRoute: '/api/admin/order-change-request-console',
            actions: ['read', 'write'],
            riskLevel: 'high',
            apiPaths: expect.arrayContaining([
              '/admin/orders/change-requests',
              '/admin/orders/{orderId}/change-request/review-events',
              '/admin/orders/{orderId}/change-request/review',
            ]),
          }),
          expect.objectContaining({
            key: 'account_management_manage',
            moduleKey: 'account-management',
            moduleTitle: '账号管理台',
            consoleRoute: '/api/admin/account-management-console',
            actions: ['read', 'write'],
            riskLevel: 'high',
            apiPaths: expect.arrayContaining([
              '/admin/auth/accounts',
              '/admin/auth/accounts/report',
              '/admin/auth/accounts/export',
              '/admin/auth/accounts/batch-status',
              '/admin/auth/accounts/batch-revoke-sessions',
              '/admin/auth/accounts/{userId}',
              '/admin/auth/accounts/{userId}/status',
              '/admin/auth/accounts/{userId}/revoke-sessions',
            ]),
          }),
          expect.objectContaining({
            key: 'evaluation_audit_read',
            moduleKey: 'evaluation-audit',
            actions: ['read'],
            riskLevel: 'sensitive',
            apiPaths: expect.arrayContaining([
              '/admin/evaluations',
              '/admin/evaluations/{evaluationId}',
              '/admin/evaluations/{evaluationId}/attachments',
            ]),
          }),
          expect.objectContaining({
            key: 'finance_manage',
            moduleKey: 'finance',
            moduleTitle: '财务操作台',
            consoleRoute: '/api/admin/finance-console',
            actions: ['read', 'write'],
            riskLevel: 'high',
            apiPaths: expect.arrayContaining([
              '/admin/finance/report',
              '/admin/finance/payments',
              '/admin/finance/payments/{paymentId}',
              '/admin/finance/refunds/{refundId}',
              '/admin/finance/refunds/{refundId}/retry',
              '/admin/finance/settlements/{settlementId}',
              '/admin/finance/withdrawals/{withdrawalId}',
              '/admin/finance/withdrawals/batch-review',
            ]),
          }),
        ]),
      }),
    );
  });
});
