import { StyleSheet } from 'react-native';

export const colors = {
  background: '#F3F6F4',
  surface: '#FFFFFF',
  surfaceMuted: '#F8FAF8',
  text: '#16211C',
  textSecondary: '#52615A',
  textMuted: '#7B8A83',
  border: '#DDE6E1',
  teal: '#0E6F5C',
  tealDark: '#094A3E',
  tealSoft: '#DDF1EC',
  amber: '#D97904',
  amberSoft: '#FFF2DC',
  blueSoft: '#E4F0FF',
};

const shadows = {
  shadowColor: '#17372E',
  shadowOffset: { width: 0, height: 8 },
  shadowOpacity: 0.08,
  shadowRadius: 18,
  elevation: 3,
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  authScreen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  authContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingVertical: 24,
    justifyContent: 'center',
    gap: 16,
  },
  authHero: {
    gap: 8,
  },
  authKicker: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  authTitle: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '900',
  },
  authDescription: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  authCard: {
    borderRadius: 8,
    backgroundColor: colors.surface,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows,
  },
  authTabRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  authTabButton: {
    flex: 1,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
  },
  authTabButtonActive: {
    backgroundColor: colors.tealDark,
    borderColor: colors.tealDark,
  },
  authTabText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '800',
  },
  authTabTextActive: {
    color: colors.surface,
  },
  authForm: {
    gap: 12,
  },
  authField: {
    gap: 6,
  },
  authLabel: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '800',
  },
  authInput: {
    minHeight: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    color: colors.text,
    paddingHorizontal: 12,
    fontSize: 15,
  },
  authMultilineInput: {
    minHeight: 96,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  authInlineRow: {
    flexDirection: 'row',
    gap: 8,
  },
  authInlineInput: {
    flex: 1,
  },
  authInlineButton: {
    minWidth: 100,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.tealSoft,
    paddingHorizontal: 12,
  },
  authInlineButtonText: {
    color: colors.tealDark,
    fontSize: 13,
    fontWeight: '800',
  },
  authNotice: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  authAgreementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  authCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authCheckboxActive: {
    backgroundColor: colors.tealDark,
    borderColor: colors.tealDark,
  },
  authCheckboxMark: {
    color: colors.surface,
    fontSize: 11,
    fontWeight: '900',
  },
  authAgreementText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  authPrimaryButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.tealDark,
  },
  authPrimaryButtonText: {
    color: colors.surface,
    fontSize: 16,
    fontWeight: '900',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 16,
  },
  draftContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 14,
  },
  draftTopBar: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  draftBackButton: {
    minHeight: 40,
    minWidth: 76,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
  },
  draftBackText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '800',
  },
  draftTitleGroup: {
    flex: 1,
  },
  draftKicker: {
    color: colors.textMuted,
    fontSize: 12,
  },
  draftTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
  },
  draftBadge: {
    minHeight: 28,
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.amberSoft,
    paddingHorizontal: 10,
  },
  draftBadgeText: {
    color: colors.amber,
    fontSize: 12,
    fontWeight: '800',
  },
  draftStepper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  draftStep: {
    minHeight: 34,
    borderRadius: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  draftStepActive: {
    backgroundColor: colors.tealSoft,
    borderColor: colors.tealSoft,
  },
  draftStepText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '800',
  },
  draftStepTextActive: {
    color: colors.tealDark,
  },
  draftCard: {
    borderRadius: 8,
    backgroundColor: colors.surface,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
    ...shadows,
  },
  draftSectionTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '900',
  },
  draftChoiceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  draftChoiceButton: {
    minHeight: 38,
    borderRadius: 8,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  draftChoiceButtonActive: {
    backgroundColor: colors.tealDark,
    borderColor: colors.tealDark,
  },
  draftChoiceText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '800',
  },
  draftChoiceTextActive: {
    color: colors.surface,
  },
  draftNotice: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  draftInlineSection: {
    gap: 8,
  },
  draftFieldLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  draftPrefillNotice: {
    borderRadius: 8,
    backgroundColor: colors.tealSoft,
    borderWidth: 1,
    borderColor: colors.tealSoft,
    padding: 12,
  },
  draftPrefillNoticeText: {
    color: colors.tealDark,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
  },
  draftPrefillNoticeAction: {
    marginTop: 10,
  },
  draftPrimaryButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.tealDark,
  },
  draftPrimaryButtonText: {
    color: colors.surface,
    fontSize: 16,
    fontWeight: '900',
  },
  draftSecondaryButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  draftSecondaryButtonText: {
    color: colors.textSecondary,
    fontSize: 15,
    fontWeight: '800',
  },
  detailContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 14,
  },
  detailTopBar: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  detailTitleGroup: {
    flex: 1,
  },
  detailTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
  },
  detailCard: {
    borderRadius: 8,
    backgroundColor: colors.surface,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
    ...shadows,
  },
  detailRoute: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 22,
  },
  detailMeta: {
    color: colors.textMuted,
    fontSize: 12,
  },
  detailInlineGroup: {
    gap: 10,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  detailTimeline: {
    gap: 10,
  },
  detailTimelineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  detailTimelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.border,
  },
  detailTimelineDotActive: {
    backgroundColor: colors.tealDark,
  },
  detailTimelineText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  detailTimelineTextActive: {
    color: colors.text,
  },
  detailGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  detailInfoCard: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: colors.surface,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 6,
  },
  detailInfoLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  detailInfoValue: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 20,
  },
  detailInfoHint: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  detailPrimaryButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.tealDark,
  },
  detailPrimaryButtonText: {
    color: colors.surface,
    fontSize: 16,
    fontWeight: '900',
  },
  detailSecondaryButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  detailSecondaryButtonText: {
    color: colors.textSecondary,
    fontSize: 15,
    fontWeight: '800',
  },
  detailNoticeCard: {
    borderRadius: 8,
    backgroundColor: colors.amberSoft,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.amberSoft,
  },
  detailNoticeText: {
    color: colors.amber,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
  },
  driverInfoCard: {
    borderRadius: 8,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    gap: 10,
  },
  driverInfoHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  driverName: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '900',
  },
  driverMeta: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  driverRatingPill: {
    minHeight: 26,
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.tealSoft,
    paddingHorizontal: 8,
  },
  driverRatingText: {
    color: colors.tealDark,
    fontSize: 12,
    fontWeight: '900',
  },
  driverInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  driverQuoteCard: {
    borderRadius: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    gap: 12,
  },
  driverQuoteFooter: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 12,
  },
  driverQuoteTextGroup: {
    flex: 1,
    gap: 2,
  },
  driverQuotePrice: {
    color: colors.amber,
    fontSize: 18,
    fontWeight: '900',
  },
  driverQuoteButton: {
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.tealDark,
    paddingHorizontal: 12,
  },
  driverQuoteButtonText: {
    color: colors.surface,
    fontSize: 13,
    fontWeight: '900',
  },
  ordersContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 14,
  },
  ordersTopBar: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  ordersTitleGroup: {
    flex: 1,
  },
  ordersTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
  },
  ordersTabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  ordersTab: {
    minHeight: 36,
    borderRadius: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ordersTabActive: {
    backgroundColor: colors.tealDark,
    borderColor: colors.tealDark,
  },
  ordersTabText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '800',
  },
  ordersTabTextActive: {
    color: colors.surface,
  },
  ordersSearchInput: {
    minHeight: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    paddingHorizontal: 12,
    fontSize: 14,
  },
  ordersEmptyState: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 16,
    gap: 6,
  },
  ordersEmptyTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
  },
  ordersEmptyText: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  topBar: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  cityPill: {
    minHeight: 40,
    minWidth: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cityText: {
    color: colors.tealDark,
    fontSize: 15,
    fontWeight: '700',
  },
  topTitleGroup: {
    flex: 1,
  },
  pageKicker: {
    color: colors.textMuted,
    fontSize: 12,
  },
  pageTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
  },
  topActions: {
    flexDirection: 'row',
    gap: 8,
  },
  iconButton: {
    minHeight: 40,
    minWidth: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  iconButtonText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  badge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: colors.amber,
    paddingHorizontal: 4,
  },
  badgeText: {
    color: colors.surface,
    fontSize: 10,
    fontWeight: '800',
  },
  verificationPanel: {
    padding: 16,
    borderRadius: 8,
    backgroundColor: colors.tealDark,
    ...shadows,
  },
  panelHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  greeting: {
    color: colors.surface,
    fontSize: 20,
    fontWeight: '800',
  },
  profileIdentityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
    gap: 12,
  },
  profileAvatar: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: colors.tealSoft,
  },
  profileAvatarText: {
    color: colors.tealDark,
    fontSize: 18,
    fontWeight: '800',
  },
  profileBadgeColumn: {
    alignItems: 'flex-end',
    gap: 8,
  },
  subtleText: {
    marginTop: 6,
    color: '#C7DDD5',
    fontSize: 13,
    lineHeight: 18,
  },
  verifiedBadge: {
    minHeight: 28,
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.tealSoft,
    paddingHorizontal: 10,
  },
  verifiedBadgeText: {
    color: colors.tealDark,
    fontSize: 12,
    fontWeight: '800',
  },
  metricRow: {
    marginTop: 18,
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.16)',
    paddingTop: 14,
  },
  metricItem: {
    flex: 1,
  },
  metricValue: {
    color: colors.surface,
    fontSize: 17,
    fontWeight: '800',
  },
  metricLabel: {
    marginTop: 4,
    color: '#B9D3CA',
    fontSize: 12,
  },
  primaryPanel: {
    minHeight: 118,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    borderRadius: 8,
    backgroundColor: colors.surface,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows,
  },
  primaryTextGroup: {
    flex: 1,
  },
  primaryTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '900',
  },
  primaryDescription: {
    marginTop: 6,
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  primaryMeta: {
    marginTop: 8,
    color: colors.amber,
    fontSize: 12,
    fontWeight: '800',
  },
  primaryButton: {
    minWidth: 76,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.amber,
  },
  primaryButtonText: {
    color: colors.surface,
    fontSize: 16,
    fontWeight: '900',
  },
  pressedButton: {
    opacity: 0.82,
  },
  section: {
    gap: 10,
  },
  sectionHeader: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
  },
  sectionAction: {
    color: colors.teal,
    fontSize: 13,
    fontWeight: '800',
  },
  statusGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  statusCard: {
    width: '48.5%',
    minHeight: 112,
    justifyContent: 'space-between',
    borderRadius: 8,
    backgroundColor: colors.surface,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  pressedCard: {
    opacity: 0.76,
  },
  statusCount: {
    color: colors.tealDark,
    fontSize: 26,
    fontWeight: '900',
  },
  statusLabel: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
  },
  statusDescription: {
    color: colors.textMuted,
    fontSize: 12,
  },
  routeList: {
    gap: 10,
  },
  routeCard: {
    borderRadius: 8,
    backgroundColor: colors.surface,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  routeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  routeName: {
    flex: 1,
    color: colors.text,
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 21,
  },
  routeAction: {
    color: colors.amber,
    fontSize: 12,
    fontWeight: '800',
  },
  messageHeaderMeta: {
    alignItems: 'flex-end',
    gap: 4,
  },
  messageCategoryText: {
    color: colors.tealDark,
    fontSize: 12,
    fontWeight: '800',
  },
  routeAddress: {
    marginTop: 8,
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  routeMeta: {
    marginTop: 10,
    color: colors.textMuted,
    fontSize: 12,
  },
  orderList: {
    gap: 10,
  },
  orderCard: {
    borderRadius: 8,
    backgroundColor: colors.surface,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  orderTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  statusPill: {
    minHeight: 28,
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.blueSoft,
    paddingHorizontal: 10,
  },
  statusPillText: {
    color: colors.tealDark,
    fontSize: 12,
    fontWeight: '900',
  },
  orderId: {
    flex: 1,
    color: colors.textMuted,
    fontSize: 12,
    textAlign: 'right',
  },
  orderRoute: {
    marginTop: 12,
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 22,
  },
  orderMetaRow: {
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  orderMetaText: {
    color: colors.textSecondary,
    fontSize: 12,
    backgroundColor: colors.surfaceMuted,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  orderExceptionSummary: {
    marginTop: 12,
    gap: 4,
    borderRadius: 8,
    backgroundColor: colors.amberSoft,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  orderExceptionSummaryTitle: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
  },
  orderExceptionSummaryText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  orderBottomRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 12,
  },
  orderPrice: {
    color: colors.amber,
    fontSize: 18,
    fontWeight: '900',
  },
  orderTime: {
    marginTop: 4,
    color: colors.textMuted,
    fontSize: 12,
  },
  secondaryButton: {
    minHeight: 40,
    minWidth: 82,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.tealSoft,
    paddingHorizontal: 12,
  },
  secondaryButtonText: {
    color: colors.tealDark,
    fontSize: 13,
    fontWeight: '900',
  },
});
